name: Daily Data Extraction

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta el script a las 00:00 UTC todos los días

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.2' # Asegúrate de usar la versión de Python que necesites

      - name: Install dependencies
        run: |
          pip install selenium pandas

      - name: Run data extraction script
        run: |
          python load_CME.py

      - name: Commit and push CSV file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add fed_rate_data.csv
          git commit -m 'Update fed_rate_data.csv'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
